# Generated by Django 4.2.6 on 2023-11-01 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, unique=True)),
                ('monto_afiliado', models.IntegerField()),
                ('monto_adherente', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.disciplinas')),
            ],
        ),
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroSocio', models.IntegerField(unique=True)),
                ('dni', models.IntegerField(unique=True)),
                ('apellido', models.CharField(blank=True, max_length=200)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('tipo_socio', models.PositiveSmallIntegerField(choices=[(0, 'afiliado'), (1, 'adherente')])),
                ('disciplinas', models.ManyToManyField(through='socios.Inscripcion', to='socios.disciplinas')),
            ],
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socios'),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.IntegerField()),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.disciplinas')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socios')),
            ],
        ),
    ]
