# Generated by Django 4.2 on 2023-11-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_inscripcion_fecha_reinicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
