# Generated by Django 4.2.6 on 2023-11-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0004_alter_factura_fecha_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_vencido',
            field=models.DateField(blank=True, null=True),
        ),
    ]
